name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
    #   - uses: actions/setup-python@v5
    #   - uses: akaihola/darker@v2.1.1
    #     with:
    #       options: "--check --diff --isort --color"
    #       src: "."
    #       version: "~=2.1.1"
    #       lint: "ruff"

      - uses: chartboost/ruff-action@491342200cdd1cf4d5132a30ddc546b3b5bc531b
        with:
            changed-files: 'true'